v1.0 of check_EGI-SVG-2013-5890
git-svn-id: http://svn.hellasgrid.gr/svn/code.grid.auth.gr/grid-monitoring-probes-eu.egi.sec/trunk@2297 d7ba6b9b-056d-0410-bae2-a7bde154aea1

diff --git a/src/probes/check_EGI-SVG-2013-5890 b/src/probes/check_EGI-SVG-2013-5890
--- a/src/probes/check_EGI-SVG-2013-5890
+++ b/src/probes/check_EGI-SVG-2013-5890
@@ -2,7 +2,7 @@
 
 # nagios check for cvmfs local root exploit
 
-PROBE_VERSION="v0.7"
+PROBE_VERSION="v1.0"
 
 NAGIOS_OK=0
 NAGIOS_WARNING=1
@@ -12,36 +12,38 @@ NAGIOS_UNKNOWN=3
 HASH2_0="639fa7fc467b67514671769dd1641d98"
 HASH2_1="28f1694bb45236c5a70505d19b0f5134"
 
-command -v cvmfs2 &>/dev/null
-if [ $? -ne 0 ]; then
-   MSG="no cvmfs package found"
-   echo "OK: $MSG"
-   exit $NAGIOS_OK
-fi
-
- VERSION=`echo "$(cvmfs2 -V 2>&1)" | sed -nre 's/[^0-9]*(([0-9]+\.)*[0-9]+).*/\1/p'`
- BRANCH=`echo "$(cvmfs2 -V 2>&1)" | sed -nre 's/[^0-9]+(([0-9]+\.){1}[0-9]+).*/\1/p'`
- BUILD=`echo $VERSION | sed -nre 's/([0-9]+\.)*//p'`
-
-if [ $BRANCH == 2.0 ] && (( "$BUILD" >= "22" )); then
-    MSG="Package version >= 2.0.22"
-elif [ $BRANCH == 2.1 ] && (( "$BUILD" >= "14" )); then
-    MSG="Package version >= 2.1.14"
-else (echo "${HASH2_0}  /etc/auto.cvmfs" | md5sum --check --status) || 
-     (echo "${HASH2_1}  /etc/auto.cvmfs" | md5sum --check --status);
-    MSG="found valid hotfix"
-fi
-
-MD5SUM=$(md5sum /etc/auto.cvmfs)
-
-if [ -z "$MSG" ]; then
-  echo "CRITICAL: ${VERSION} package found at `hostname` node  without hotfix"
-  echo "MD5 hash found ${MD5SUM}"
-  echo "probe version ${PROBE_VERSION}"
-  exit $NAGIOS_ERROR
+if !(command -v cvmfs2 &>/dev/null); then
+   MSG="no cvmfs found"
+   RC=$NAGIOS_OK
 else
-  echo "OK: $MSG"
-  echo "probe version ${PROBE_VERSION}"
-  exit $NAGIOS_OK
+  CVMFS2V=$(cvmfs2 -V 2>&1)
+  VERSION=${CVMFS2V##* }
+  BRANCH=${VERSION%.*}
+  BUILD=${VERSION##*.}
+  if [ $BRANCH == 2.0 ] && (( "$BUILD" >= "22" )); then
+    MSG=">= 2.0.22"
+    RC=$NAGIOS_OK
+  elif [ $BRANCH == 2.1 ] && (( "$BUILD" >= "14" )); then
+    MSG=">= 2.1.14"
+    RC=$NAGIOS_OK
+  elif (echo "${HASH2_0}  /etc/auto.cvmfs" | md5sum --check --status) || 
+       (echo "${HASH2_1}  /etc/auto.cvmfs" | md5sum --check --status); then
+    MSG="with applied hotfix"
+    RC=$NAGIOS_OK
+  else
+    MSG="without hotfix"
+  fi
+  MSG="cvmfs version $VERSION found $MSG at $HOSTNAME"
+  MSG="$MSG\\nMD5 hash $(md5sum /etc/auto.cvmfs)"
 fi
+
+case $RC in
+  $NAGIOS_OK      ) echo -e "OK: $MSG";;
+  $NAGIOS_WARNING ) echo -e "WARNING: $MSG";;
+  $NAGIOS_ERROR   ) echo -e "ERROR: $MSG";;
+  $NAGIOS_UNKNOWN ) echo -e "UNKNOWN: $MSG";;
+esac
+
+echo "probe version ${PROBE_VERSION}"
+exit $RC
 
