Moved to newer pakiti SF version
git-svn-id: http://svn.hellasgrid.gr/svn/code.grid.auth.gr/grid-monitoring-probes-org.sam.sec/trunk@1027 d7ba6b9b-056d-0410-bae2-a7bde154aea1

diff --git a/src/wnjob/org.sam.sec/probes/org.sam.sec/pakiti b/src/wnjob/org.sam.sec/probes/org.sam.sec/pakiti
--- a/src/wnjob/org.sam.sec/probes/org.sam.sec/pakiti
+++ b/src/wnjob/org.sam.sec/probes/org.sam.sec/pakiti
@@ -1,21 +1,16 @@
 #!/bin/bash
+cur_path=`dirname $0`
+result=`${cur_path}/pakiti2-client -c ${cur_path}/pakiti2-client.conf 2>&1` # | sed ':a;N;$!ba;s/\n/\\n/g'#`
+exit_status=$?
 
-RESULT=`eval ./pakiti2-client -c pakiti2-client.conf`
-server_count=`echo $RESULT | awk -F"Requested report to " '{print $2}'|awk -F" server" '{print $1}'`
-server_ok_count=`echo $RESULT | awk -F"Reported correctly to " '{print $2}'|awk -F" server" '{print $1}'`
-
-if [ $server_ok_count == $server_count ]; then
-  echo "OK: Pakiti reported correctly to $server_count servers."
-  echo "Pakiti reported correctly to all the configured servers."
-  exit 0
+if [ ${exit_status} == 0 ]; then
+  echo "OK: Pakiti reported correctly to all the configured servers."
 else
-  if [ $server_ok_count != 0 ]; then
+  if [ ${exit_status} == 1 ]; then
     echo "WARNING: Pakiti didn't report to all configured servers."
-    echo "Pakiti reported on $server_ok_count out of $server_count servers."
-    exit 1
   else
     echo "ERROR: There was an error on pakiti reporting."
-    echo "Pakiti failed to report to any server."
-    exit 2
   fi
 fi
+echo ${result}|sed -e "s# ERROR(s)#\nERROR(s)#g"
+exit ${exit_status}
diff --git a/src/wnjob/org.sam.sec/probes/org.sam.sec/pakiti2-client b/src/wnjob/org.sam.sec/probes/org.sam.sec/pakiti2-client
--- a/src/wnjob/org.sam.sec/probes/org.sam.sec/pakiti2-client
+++ b/src/wnjob/org.sam.sec/probes/org.sam.sec/pakiti2-client
@@ -5,7 +5,7 @@ VERSION="4"
 CONF='/etc/pakiti2/pakiti2-client.conf'
 SERVERS="notspecified"
 SERVER_URL="/feed/"
-METHOD="openssl"
+METHOD="autodetect"
 OPENSSL_BIN=`which openssl`
 CURL_BIN=`which curl`
 TAG="Pakiti client"
@@ -20,19 +20,44 @@ usage=$0" [-v] [-h] [-d] [-c configuration file]\n\t-v: verbose output\n\t-h: th
 
 VERBOSE=0
 DEBUG=0
+ERROR=0
 TMPFILE=`mktemp`
+TMPERR=`mktemp`
+
+function quit {
+  EXIT=$1
+  # If there were any errors, print them out
+  if [ "X$2" != "X" ]; then
+    if [ $1 -eq 1 ]; then
+      echo "WARNING: $2" 1>&2
+    elif [ $1 -gt 1 ]; then
+      echo "ERROR: $2" 1>&2
+    fi
+  fi
+  if [ ${ERROR} -eq 1 ]; then
+    echo -n "ERROR(s): " 1>&2
+    cat ${TMPERR} 1>&2
+    if [ ${EXIT} -eq 0 ]; then
+      EXIT=1
+    fi
+  fi
+
+  rm -f ${TMPFILE}
+  rm -f ${TMPERR}
+  exit ${EXIT}
+}
 
 # Getting options
-while getopts "dvhc" options; do
+while getopts "dvhc:" options; do
   case $options in
     c ) CONF=$OPTARG;;
     v ) VERBOSE=1;;
     d ) DEBUG=1
-				VERBOSE=1;;
+	VERBOSE=1;;
     h ) echo -e "$usage"
-         exit 1;;
+	quit 1;;
     * ) echo -e "$usage"
-          exit 1;;
+	quit 1;;
   esac
 done
 
@@ -40,7 +65,7 @@ if [ "X${CONF}" = "X" -o ! -f "${CONF}" ]
 then
 	if [ ${VERBOSE} -eq 1 ]; 
 		then
-	  echo "Configuration file is missing at '${CONF}', using defaults!"
+	  echo "Configuration file is missing at '${CONF}', using defaults!" 1>&2
 	fi
 else
 
@@ -49,12 +74,12 @@ else
 	L_SERVER_URL=`grep server_url ${CONF} | grep -v \# | awk  -F "=" '{print $2}' | tr -d " "`
 	L_OPENSSL_BIN=`grep openssl_path ${CONF} | grep -v \# | awk -F "=" '{print $2}'`
 	L_CURL_BIN=`grep curl_path ${CONF} | grep -v \# | awk -F "=" '{print $2}'`
-	L_CA_PATH=`grep ca_certificate ${CONF} | grep -v \# | awk -F "=" '{print $2}'`
+	L_CA_PATH=`grep ca_certificate ${CONF} | grep -v \# | awk -F "=" '{print $2}' | tr -d " "`
 	L_HOST_CERT=`grep host_cert ${CONF} | grep -v \# | awk -F "=" '{print $2}'`
 	L_TAG=`grep tag ${CONF} | grep -v \# | awk -F "=" '{print $2}' | tr -d " "`
 	L_METHOD=`grep connection_method ${CONF} | grep -v \# | awk -F "=" '{print $2}' | tr -d " "`
-	L_REPORT=`greop report ${CONF} | grep -v \# | awk -F "=" '{print $2}' | tr -d " "`
-	L_SERVER_REPORT_STATS=`grep server_report_stats ${CONF} | grep -v \# | awk -F "=" '{print $2}' | tr -d " "`
+	L_REPORT=`grep report ${CONF} | grep -v \# | awk -F "=" '{print $2}' | tr -d " "`
+	L_SERVER_REPORT_STATS=`grep server_rep_stats ${CONF} | grep -v \# | awk -F "=" '{print $2}' | tr -d " "`
 	L_IS_PROXY=`grep is_proxy ${CONF} | grep -v \# | awk -F "=" '{print $2}' | tr -d " "`
 	L_INTERFACE=`grep interface ${CONF} | grep -v \# | awk -F "=" '{print $2}' | tr -d " "`
 
@@ -111,11 +136,24 @@ else
 	        echo -e "Preparing the list of installed packages...";
 	fi
 fi
+
+# If method is autodetect, then detect which transport is available
+if [ "X${METHOD}" = "Xautodetect" ]; then
+  if [ -x ${CURL_BIN} ]; then
+    METHOD="curl"
+  elif [ -x ${OPENSSL_BIN} ]; then
+    METHOD="openssl"
+  else
+    quit 2 "No transport method available, install openssl or curl"
+  fi
+fi
+
 # If proxy mode is enabled, then method cannot be stdout
 if [ ${IS_PROXY} -eq 1 -a "X${METHOD}" = "Xstdout" ]; then
-  echo "ERROR: Proxy and stdout method cannot be used together"
-  exit
+  quit 2 "Proxy and stdout method cannot be used together"
 fi
+
+
 # If we are in proxy mode, read the data from stdin
 if [ ${IS_PROXY} -eq 1 ]; then
   # Parse firs line which contains host,arch,os,...
@@ -136,8 +174,7 @@ if [ ${IS_PROXY} -eq 1 ]; then
 	if [ "X${VAR}" = "Xversion" ]; then
 	  # Check if the client using the same version
 	  if [ "X${VAL}" != "X${VERSION}" ]; then
-	    echo "ERROR: Client is using version ${VAL}, but proxy is using ${VERSION}"
-	    exit
+	    quit 2 "Client is using version ${VAL}, but proxy is using ${VERSION}"
 	  fi
 	fi
 	if [ "X${VAR}" = "Xtype" ]; then
@@ -155,8 +192,8 @@ if [ ${IS_PROXY} -eq 1 ]; then
 	if [ "X${VAR}" = "Xarch" ]; then
 	  ARCH=${VAL}
 	fi
-	if [ "X${VAR}" = "Xos" ]; then
-	  OS=${VAL}
+	if [ "X${VAR}" = "Xsite" ]; then
+	  SITE=${VAL}
 	fi
       done
       ARGSDONE=1
@@ -175,6 +212,12 @@ else
   ARCH=`uname -m`
   PKGS=""
   TYPE=""
+  SITE=""
+
+  # If site variable is set, then us it
+  if [ "X${SITE_NAME}" != "X" ]; then
+    SITE=${SITE_NAME}
+  fi
 
   # Get list of packages by method which is available on the host
   if [ ! -z "`which rpm`"  -a  -x "`which rpm`"  ]; then
@@ -189,72 +232,44 @@ else
   	TYPE="dpkg"
      fi
   fi
-
-  # Looking for type of OS
-  OS="unknown"
-  for i in /etc/lsb-release /etc/debian_version /etc/fermi-release /etc/redhat-release /etc/fedora-release /etc/SuSE-release; do
-    if [ -f $i ]; then
-      case "${i}" in
-	/etc/lsb-release)
-	 TMP_OS=`grep DISTRIB_DESCRIPTION ${i}`
-	 OS=`echo ${TMP_OS} | sed -e 's/DISTRIB_DESCRIPTION="\(.*\)"/\1/'`
-	 if [ -z "${OS}" ]; then
-		  TMP_OS=`grep  DISTRIB_DESC ${i}`
-		  OS=`echo ${TMP_OS} | sed -e 's/DISTRIB_DESC="\(.*\)"/\1/'`
-	 fi
-	 ;;
-	/etc/debian_version)
-	 OS="Debian `cat ${i}`"
-	 ;;
-	/etc/fermi-release|/etc/redhat-release|/etc/fedora-release)
-	 OS=`cat ${i}`
-	 ;;
-	/etc/SuSE-release)
-	 OS=`grep -i suse ${i}`
-	 ;;
-      esac
-    fi
-    if [ "${OS}" != "unknown" ]; then
-      break
-    fi
-  done
 fi
+
 
 SERVERS_REPORTED_CORRECTLY=0
 # Iterate over all servers
 for SERVER in $SERVERS; do 
 	if [ "X${METHOD}" = "Xopenssl" ]; then
 		# Preparing openssl s_client string
-		OPENSSL_BIN="${OPENSSL_BIN} s_client";
+		OPENSSL="${OPENSSL_BIN} s_client";
 		
 		if [ "X${CA_PATH}" != "X" ]; 
 			then 
-			OPENSSL_BIN="${OPENSSL_BIN} -CApath \"${CA_PATH}\"";
+			OPENSSL="${OPENSSL} -CApath \"${CA_PATH}\"";
 		fi
 		
 		if [ ${VERBOSE} -eq 1 ];
 		        then
-		        OPENSSL_BIN="${OPENSSL_BIN} -msg";
+		        OPENSSL="${OPENSSL} -msg";
 			echo -e "Sending to the server...";
 		else
-			OPENSSL_BIN="${OPENSSL_BIN} -quiet";
+			OPENSSL="${OPENSSL} -quiet";
 		fi
 		
 		if [ ${DEBUG} -eq 1 ];
 		        then
-		        OPENSSL_BIN="${OPENSSL_BIN} -debug";
+		        OPENSSL="${OPENSSL} -debug";
 		else
-			OPENSSL_BIN="${OPENSSL_BIN} -quiet";
+			OPENSSL="${OPENSSL} -quiet";
 		fi
 		if [ "X${HOST_CERT}" != "X" ];
 			then
-			OPENSSL_BIN="${OPENSSL_BIN} -cert \"${HOST_CERT}\"";
+			OPENSSL="${OPENSSL} -cert \"${HOST_CERT}\"";
 		fi
 	
 		# Format of the SERVER variable is hostname:port
-		OPENSSL_BIN="${OPENSSL_BIN} -connect ${SERVER}";
+		OPENSSL="${OPENSSL} -connect ${SERVER}";
 		
-		POST_DATA="type=${TYPE}&host=${REPHOST}&site=${SITE_NAME}&os=${OS}&arch=${ARCH}&tag=${TAG}&kernel=${KERNEL}&version=${VERSION}&report=${REPORT}&proxy=${IS_PROXY}&pkgs=";
+		POST_DATA="type=${TYPE}&host=${REPHOST}&arch=${ARCH}&tag=${TAG}&kernel=${KERNEL}&version=${VERSION}&report=${REPORT}&proxy=${IS_PROXY}&site=${SITE}&pkgs=";
 		POST_DATA_SIZE=`echo -n ${POST_DATA} | wc -m`;
 		FILE_SIZE=`cat ${TMPFILE} | wc -c`
 		let POST_DATA_SIZE=${POST_DATA_SIZE}+${FILE_SIZE}-1
@@ -263,11 +278,7 @@ for SERVER in $SERVERS; do
 		 
 		POST_DATA="${POST_HTTP_HEADER}${POST_DATA}";
 		
-		if [ ${VERBOSE} -eq 1 -o ${DEBUG} -eq 1 ]; then
-			COMMAND="echo -e \"${POST_DATA}\" | cat - ${TMPFILE} | ${OPENSSL_BIN}";
-		else
-			COMMAND="echo -e \"${POST_DATA}\" | cat - ${TMPFILE} | ${OPENSSL_BIN} 2>/dev/null";
-		fi
+		COMMAND="echo -e \"${POST_DATA}\" | cat - ${TMPFILE} | ${OPENSSL}";
 	
 	elif [ "X${METHOD}" = "Xcurl" ]; then
 		CURL=""
@@ -289,7 +300,8 @@ for SERVER in $SERVERS; do
 		        CURL="${CURL} -F verbose=\"1\"";
 		        echo -e "Sending to the server with curl...";
 		else	
-			CURL="${CURL} -s";	
+			# Be silent, but print error messages
+			CURL="${CURL} --silent --show-error";	
 		fi
 		
 		if [ ${DEBUG} -eq 1 ];
@@ -304,29 +316,31 @@ for SERVER in $SERVERS; do
 		
 		CURL="${CURL} -F type=\"${TYPE}\"";
 		CURL="${CURL} -F host=\"${REPHOST}\"";
-		CURL="${CURL} -F site=\"${SITE_NAME}\"";
 		CURL="${CURL} -F tag=\"${TAG}\"";
 		CURL="${CURL} -F kernel=\"${KERNEL}\"";
 		CURL="${CURL} -F arch=\"${ARCH}\"";
 		CURL="${CURL} -F version=\"${VERSION}\"";
-		CURL="${CURL} -F os=\"${OS}\"";
 		CURL="${CURL} -F report=\"${REPORT}\"";
 		CURL="${CURL} -F proxy=\"${IS_PROXY}\"";
+		CURL="${CURL} -F site=\"${SITE}\"";
 		CURL="${CURL} -F pkgs=\<${TMPFILE}";
 		COMMAND="${CURL_BIN}${CURL} https://${SERVER}${SERVER_URL}"
 	
 	elif [ "X${METHOD}" = "Xstdout" ]; then
-#		OUTFILE=`mktemp`
-		echo -e "type=\"${TYPE}\",host=\"${REPHOST}\",tag=\"${TAG}\",kernel=\"${KERNEL}\",arch=\"${ARCH}\",version=\"${VERSION}\",os=\"${OS}\",report=\"${REPORT}\"\n";
+		echo -e "type=\"${TYPE}\",host=\"${REPHOST}\",tag=\"${TAG}\",kernel=\"${KERNEL}\",arch=\"${ARCH}\",site=\"${SITE}\",version=\"${VERSION}\",report=\"${REPORT}\"\n";
 
 		cat $TMPFILE | sed -e 's/%2b/\+/g';
 	fi
 	
-	RESULT=`eval "${COMMAND}"`;
+	# Run prepared command
+	RESULT=`eval "${COMMAND} 2>>${TMPERR}"`;
 
-	if [ $? == 0 ] ; then
+	if [ $? -eq 0 ] ; then
 		SERVERS_REPORTED_CORRECTLY=`expr $SERVERS_REPORTED_CORRECTLY + 1`
-	fi 
+	else 
+		# Set ERROR if any occured
+		ERROR=1
+	fi
 
 	# Print out the results
 	if [ ${REPORT} -eq 1 ]; then
@@ -343,8 +357,14 @@ done
 
 # Print server reporting statistics
 if [ ${SERVER_REPORT_STATS} -eq 1 ]; then
-	echo "Requested report to `echo $SERVERS |wc -w ` server(s)"
-	echo "Reported correctly to $SERVERS_REPORTED_CORRECTLY server(s)"
+	SERVERS_COUNT=`echo $SERVERS |wc -w`
+	if [ ${SERVERS_COUNT} -eq  ${SERVERS_REPORTED_CORRECTLY} ]; then
+	  echo "OK: Pakiti reported correctly to $SERVERS_REPORTED_CORRECTLY server(s)"
+	elif [ ${SERVERS_REPORTED_CORRECTLY} -gt 0 ]; then
+	  quit 1 "Pakiti reported correctly only to $SERVERS_REPORTED_CORRECTLY/${SERVERS_COUNT} servers(s)"
+	else
+	  quit 2 "Pakiti failed to report to any server"
+	fi
 fi
 
-rm -f ${TMPFILE}
+quit 0
