Re-structuring org.sam.sec probe. Allowed use of multiple pakiti servers
git-svn-id: http://svn.hellasgrid.gr/svn/code.grid.auth.gr/grid-monitoring-probes-org.sam.sec/trunk@31 d7ba6b9b-056d-0410-bae2-a7bde154aea1

diff --git a/src/wnjob/org.sam.sec/probes/org.sam.sec/pakiti b/src/wnjob/org.sam.sec/probes/org.sam.sec/pakiti
--- a/src/wnjob/org.sam.sec/probes/org.sam.sec/pakiti
+++ b/src/wnjob/org.sam.sec/probes/org.sam.sec/pakiti
@@ -3,7 +3,7 @@
 VERSION="2.0.3"
 
 # Getting parameters from the configuration file
-SERVER="https://pakiti.cern.ch/feed/"
+SERVERS="https://pakiti.afroditi.hellasgrid.gr/feed/ https://pakiti.cern.ch/feed/"
 CURL_BIN="/usr/bin/curl -ks"
 CA_PATH="/etc/grid-security/certificates/"
 TAG="Nagios Pakiti probe"
@@ -14,26 +14,35 @@ RPMS=`rpm -qa --queryformat "%{installtime} NEWPAKITIRPM=%{NAME} %{EPOCH}:%{VERS
 KERNEL=`uname -r`
 CURL=""
 
-# Preparing curl string
-if [ "X${CA_PATH}" != "X" ]; 
-	then 
-	CURL="${CURL} --capath ${CA_PATH}";
-fi
-
+CURL="${CURL} --capath ${CA_PATH}";
 CURL="${CURL} -F host=\"${HOSTNAME}\"";
 CURL="${CURL} -F tag=\"${TAG}\"";
 CURL="${CURL} -F kernel=\"${KERNEL}\"";
 CURL="${CURL} -F version=\"${VERSION}\"";
 CURL="${CURL} -F rpms=\"${RPMS}'\" ";
 
-COMMAND="${CURL_BIN}${CURL}${SERVER}"
-RESULT=`eval "${COMMAND}"`
-exit_code=$?
 
-if [ $exit_code == 0 ] ; then
-    echo "summary: Pakiti reported correctly."
-    exit $SAME_OK
+server_count=0
+server_ok_count=0
+for i in $SERVERS; do
+  server_count=`expr $server_count + 1`
+  COMMAND="${CURL_BIN}${CURL}${i}"
+  RESULT=`eval "${COMMAND}"`
+  exit_code=$?
+  if [ $exit_code == 0 ] ; then
+    server_ok_count=`expr $server_ok_count + 1`
+  fi
+done
+
+if [ $server_ok_count == $server_count ]; then
+  echo "OK: Pakiti reported correctly to $server_count servers."
+  exit $SAME_OK
 else
-    echo "summary: There was an error on pakiti reporting."
+  if [ $server_ok_count != 0 ]; then
+    echo "WARNING: Pakiti reported on $server_ok_count out of $server_count servers."
+    exit $SAME_WARNING
+  else
+    echo "ERROR: There was an error on pakiti reporting."
     exit $SAME_ERROR
+  fi
 fi
