Use new pakiti-client version from cvmfs or use default client

diff --git a/src/WN-probes/Pakiti b/src/WN-probes/Pakiti
--- a/src/WN-probes/Pakiti
+++ b/src/WN-probes/Pakiti
@@ -9,17 +9,29 @@ if [ "X"$SITE_NAME == "X" ] && [ "X"$LCG_GFAL_INFOSYS != "X" ]; then
 	fi
 fi
 
-result=`${cur_path}/pakiti-client 2>&1`
-exit_status=$?
+if [ -f /cvmfs/grid.cern.ch/pakiti/bin/pakiti-client ]; then
+  result=`/cvmfs/grid.cern.ch/pakiti/bin/pakiti-client --url="https://pakiti.egi.eu/feed/" --site="${SITE_NAME}" --tag="Nagios"`
+  exit_status=$?
+  fallback=0
+else
+  result=`${cur_path}/pakiti-client 2>&1`
+  exit_status=$?
+  fallback=1
+fi
+
+if [ ${fallback} == 1 ]; then
+  fmessage="FALLBACK, "
+fi
 
 if [ ${exit_status} == 0 ]; then
-  echo "OK: Pakiti reported correctly to all the configured servers."
-else
-  if [ ${exit_status} == 1 ]; then
-    echo "WARNING: Pakiti didn't report to all configured servers."
+  if [ ${fallback} == 0 ]; then
+    echo "OK: Pakiti reported correctly to all the configured servers."
   else
-    echo "ERROR: There was an error on pakiti reporting."
+    echo "WARNING: ${fmessage}Pakiti reported correctly to all the configured servers."
   fi
+else
+    echo "ERROR: ${fmessage}There was an error on pakiti reporting."
 fi
+
 echo ${result}|sed -e "s# ERROR#\nERROR#g" -e "s# WARNING#\nWARNING#g"
 exit ${exit_status}
